### ISSUE TITLE
微信 3.9.11.15 版本小问题

### ISSUE THREAD

**Issue by xiaowuzimaxhub** [xuchengsheng/wx-dump-4j#24]
环境:
操作系统: Windows 10 专业版
微信: 3.9.11.15(目前最新)
JDK: 1.8.0_341

点击 微信数据同步 返回部分数据乱码,如下图
![微信同步数据显示不出来](https://github.com/xuchengsheng/wx-dump-4j/assets/5202715/038fe9ff-6076-41fc-affe-1939154a6be9)

点击 微信管理->联系人管理   页面无显示，后端抛 SQLException 异常 ，如下图
![联系人管理抛异常](https://github.com/xuchengsheng/wx-dump-4j/assets/5202715/bd7e1aa1-7021-47ad-ac08-b526bffae87c)

异常文本如下 
`org.springframework.jdbc.UncategorizedSQLException: 
### Cause: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: ContactLabel)
; uncategorized SQLException; SQL state [null]; error code [1]; [SQLITE_ERROR] SQL error or missing database (no such table: ContactLabel); nested exception is org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: ContactLabel)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:93)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
	at com.sun.proxy.$Proxy73.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:152)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy78.selectList(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.list(IService.java:406)
	at com.xcs.wx.repository.impl.ContactLabelRepositoryImpl.queryContactLabelAsList(ContactLabelRepositoryImpl.java:42)
	at com.xcs.wx.repository.impl.ContactLabelRepositoryImpl$$FastClassBySpringCGLIB$$fcaccbe2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.xcs.wx.repository.impl.ContactLabelRepositoryImpl$$EnhancerBySpringCGLIB$$3eafde96.queryContactLabelAsList(<generated>)
	at com.xcs.wx.service.impl.ContactServiceImpl.queryContactLabel(ContactServiceImpl.java:63)
	at com.xcs.wx.controller.ContactController.label(ContactController.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: ContactLabel)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.throwex(DB.java:989)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:535)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:908)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:116)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:531)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:328)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:369)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:90)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:60)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy96.prepare(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:90)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:64)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:333)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:110)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:81)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy95.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	... 66 more
org.springframework.jdbc.UncategorizedSQLException: 
### Cause: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: ContactLabel)
; uncategorized SQLException; SQL state [null]; error code [1]; [SQLITE_ERROR] SQL error or missing database (no such table: ContactLabel); nested exception is org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: ContactLabel)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:93)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:439)
	at com.sun.proxy.$Proxy73.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:77)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:152)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at com.sun.proxy.$Proxy78.selectList(Unknown Source)
	at com.baomidou.mybatisplus.extension.service.IService.list(IService.java:406)
	at com.xcs.wx.repository.impl.ContactLabelRepositoryImpl.queryContactLabelAsList(ContactLabelRepositoryImpl.java:42)
	at com.xcs.wx.repository.impl.ContactLabelRepositoryImpl.queryContactLabelAsMap(ContactLabelRepositoryImpl.java:32)
	at com.xcs.wx.repository.impl.ContactLabelRepositoryImpl$$FastClassBySpringCGLIB$$fcaccbe2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor.invoke(DynamicDataSourceAnnotationInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at com.xcs.wx.repository.impl.ContactLabelRepositoryImpl$$EnhancerBySpringCGLIB$$3eafde96.queryContactLabelAsMap(<generated>)
	at com.xcs.wx.service.impl.ContactServiceImpl.lambda$queryContact$0(ContactServiceImpl.java:38)
	at java.util.Optional.map(Optional.java:215)
	at com.xcs.wx.service.impl.ContactServiceImpl.queryContact(ContactServiceImpl.java:37)
	at com.xcs.wx.controller.ContactController.list(ContactController.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: ContactLabel)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.throwex(DB.java:989)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:535)
	at com.alibaba.druid.filter.FilterAdapter.connection_prepareStatement(FilterAdapter.java:908)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_prepareStatement(FilterEventAdapter.java:116)
	at com.alibaba.druid.filter.FilterChainImpl.connection_prepareStatement(FilterChainImpl.java:531)
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.prepareStatement(ConnectionProxyImpl.java:328)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:369)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:90)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:60)
	at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy96.prepare(Unknown Source)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:90)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:64)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:333)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:110)
	at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:81)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:59)
	at com.sun.proxy.$Proxy95.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:425)
	... 69 more
2024-06-12 20:18:45.198  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-17,FTSContact.db} inited
2024-06-12 20:18:45.198  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-9} closing ...
2024-06-12 20:18:45.199  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-9} closed
2024-06-12 20:18:45.199  INFO 35616 --- [io-8080-exec-10] c.b.d.d.d.DefaultDataSourceDestroyer     : dynamic-datasource close the datasource named [FTSContact.db] success,
2024-06-12 20:18:45.199  INFO 35616 --- [io-8080-exec-10] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [FTSContact.db] success
2024-06-12 20:18:45.449  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-18,HardLinkImage.db} inited
2024-06-12 20:18:45.449  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-10} closing ...
2024-06-12 20:18:45.450  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-10} closed
2024-06-12 20:18:45.450  INFO 35616 --- [io-8080-exec-10] c.b.d.d.d.DefaultDataSourceDestroyer     : dynamic-datasource close the datasource named [HardLinkImage.db] success,
2024-06-12 20:18:45.450  INFO 35616 --- [io-8080-exec-10] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [HardLinkImage.db] success
2024-06-12 20:18:45.699  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-19,HardLinkVideo.db} inited
2024-06-12 20:18:45.699  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-11} closing ...
2024-06-12 20:18:45.700  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-11} closed
2024-06-12 20:18:45.700  INFO 35616 --- [io-8080-exec-10] c.b.d.d.d.DefaultDataSourceDestroyer     : dynamic-datasource close the datasource named [HardLinkVideo.db] success,
2024-06-12 20:18:45.700  INFO 35616 --- [io-8080-exec-10] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [HardLinkVideo.db] success
2024-06-12 20:18:46.193  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-20,MicroMsg.db} inited
2024-06-12 20:18:46.193  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-12} closing ...
2024-06-12 20:18:46.195  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-12} closed
2024-06-12 20:18:46.195  INFO 35616 --- [io-8080-exec-10] c.b.d.d.d.DefaultDataSourceDestroyer     : dynamic-datasource close the datasource named [MicroMsg.db] success,
2024-06-12 20:18:46.195  INFO 35616 --- [io-8080-exec-10] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [MicroMsg.db] success
2024-06-12 20:18:47.932  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-21,MSG0.db} inited
2024-06-12 20:18:47.933  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-13} closing ...
2024-06-12 20:18:47.935  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-13} closed
2024-06-12 20:18:47.935  INFO 35616 --- [io-8080-exec-10] c.b.d.d.d.DefaultDataSourceDestroyer     : dynamic-datasource close the datasource named [MSG0.db] success,
2024-06-12 20:18:47.935  INFO 35616 --- [io-8080-exec-10] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [MSG0.db] success
2024-06-12 20:18:47.941  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-22,MSG.db} inited
2024-06-12 20:18:47.941  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-14} closing ...
2024-06-12 20:18:47.964  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-14} closed
2024-06-12 20:18:47.964  INFO 35616 --- [io-8080-exec-10] c.b.d.d.d.DefaultDataSourceDestroyer     : dynamic-datasource close the datasource named [MSG.db] success,
2024-06-12 20:18:47.964  INFO 35616 --- [io-8080-exec-10] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [MSG.db] success
2024-06-12 20:18:49.727  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-23,MSG1.db} inited
2024-06-12 20:18:49.727  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-15} closing ...
2024-06-12 20:18:49.730  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-15} closed
2024-06-12 20:18:49.731  INFO 35616 --- [io-8080-exec-10] c.b.d.d.d.DefaultDataSourceDestroyer     : dynamic-datasource close the datasource named [MSG1.db] success,
2024-06-12 20:18:49.731  INFO 35616 --- [io-8080-exec-10] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [MSG1.db] success
2024-06-12 20:18:50.005  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-24,Sns.db} inited
2024-06-12 20:18:50.006  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-16} closing ...
2024-06-12 20:18:50.008  INFO 35616 --- [io-8080-exec-10] com.alibaba.druid.pool.DruidDataSource   : {dataSource-16} closed
2024-06-12 20:18:50.009  INFO 35616 --- [io-8080-exec-10] c.b.d.d.d.DefaultDataSourceDestroyer     : dynamic-datasource close the datasource named [Sns.db] success,
2024-06-12 20:18:50.009  INFO 35616 --- [io-8080-exec-10] c.b.d.d.DynamicRoutingDataSource         : dynamic-datasource - add a datasource named [Sns.db] success
2024-06-12 20:18:50.011  INFO 35616 --- [io-8080-exec-10] c.x.w.repository.impl.MsgRepositoryImpl  : Start querying data:[MSG0.db][1718193239000]
2024-06-12 20:18:50.014  INFO 35616 --- [io-8080-exec-10] c.x.w.repository.impl.MsgRepositoryImpl  : End querying data:[MSG0.db][1718193239000]
2024-06-12 20:18:50.014  INFO 35616 --- [io-8080-exec-10] c.x.w.repository.impl.MsgRepositoryImpl  : Start querying data:[MSG1.db][1718193239000]
2024-06-12 20:18:50.019  INFO 35616 --- [io-8080-exec-10] c.x.w.repository.impl.MsgRepositoryImpl  : End querying data:[MSG1.db][1718193239000]

`

**Comment by xuchengsheng** [comment]
已解决
