### ISSUE TITLE
解密报错Invalid character found in the request target

### ISSUE THREAD

**Issue by stevenliuit** [xuchengsheng/wx-dump-4j#33]
页面可以读取到微信进程，但是无法解密
报文请求返回
data:{"success":false,"errorCode":-1,"errorMessage":"èŽ·å–å¾®ä¿¡ç§˜é’¥å¤±è´¥ï¼Œè¯·ç¨åŽå†è¯•ã€‚","page":null,"total":null,"showType":2,"data":null}
后台有个异常不知道是不是和这个有关系
2024-07-03 12:55:13.288  INFO 122132 --- [io-8080-exec-10] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in the request target [/api/database/getDatabase?wxId=tes+%3D+650+%0A[I][2024-07-03+%2B8.0+12:55:05.903][114268,+123108][mars::mmext][net_st ]. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:482) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by stevenliuit** [comment]
版本号3.9.11.17

**Comment by xuchengsheng** [comment]
页面截图一下，我看看

**Comment by stevenliuit** [comment]
> 页面截图一下，我看看

我加你好友吧

**Comment by xuchengsheng** [comment]
已解决
