### ISSUE TITLE
SQLException

### ISSUE THREAD

**Issue by qzpzp** [xuchengsheng/wx-dump-4j#57]
2024-09-14 23:48:02.809 ERROR 19208 --- [reate-373163008] com.alibaba.druid.pool.DruidDataSource   : create connection SQLException, url: jdbc:sqlite:xxx\program\wx-dump-4j\data\db\wxid_xdscehqkm8tk22\ChatMsg.db, errorCode 0, state null

java.sql.SQLException: path to 'xxx\program\wx-dump-4j\data\db\wxid_xdscehqkm8tk22\ChatMsg.db': 'xxx\program\wx-dump-4j\data\db' does not exist
	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:215) ~[sqlite-jdbc-3.34.0.jar:na]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) ~[sqlite-jdbc-3.34.0.jar:na]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[sqlite-jdbc-3.34.0.jar:na]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[sqlite-jdbc-3.34.0.jar:na]
	at org.sqlite.JDBC.createConnection(JDBC.java:115) ~[sqlite-jdbc-3.34.0.jar:na]
	at org.sqlite.JDBC.connect(JDBC.java:90) ~[sqlite-jdbc-3.34.0.jar:na]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:118) ~[druid-1.2.20.jar:na]
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:232) ~[druid-1.2.20.jar:na]
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:112) ~[druid-1.2.20.jar:na]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1706) ~[druid-1.2.20.jar:na]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1801) ~[druid-1.2.20.jar:na]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2946) ~[druid-1.2.20.jar:na]
	

这个连接的是我克隆下来的地址 不是微信数据的地址 所以没有这个文件 这个位置在哪修改

**Comment by xuchengsheng** [comment]
你是mac电脑的吗
